# This file is auto-generated by the GymFlow CI/CD pipeline
# It contains the SQL needed to set up the complete database schema
# Run this in Supabase SQL Editor or use: supabase db push

-- =====================================================
-- GYMFLOW DATABASE MIGRATION - v1.0
-- Run all migrations in order: 0001 -> 0002 -> 0003 -> 0004 -> 0005
-- =====================================================

-- MIGRATION 0004: Member Auth & Auth Linkage
-- =====================================================

-- 1. Add member authentication columns
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS is_verified boolean NOT NULL DEFAULT false;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS verification_code text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS verification_expires_at timestamptz;

-- 2. Add indexes for member auth
CREATE INDEX IF NOT EXISTS idx_members_phone ON public.members(phone);
CREATE INDEX IF NOT EXISTS idx_members_email ON public.members(email);
CREATE INDEX IF NOT EXISTS idx_members_verification_code ON public.members(verification_code);

-- 3. Link public.users to auth.users based on email when an auth user is created or signs in
CREATE OR REPLACE FUNCTION public.handle_auth_user_link()
RETURNS trigger AS $$
BEGIN
  UPDATE public.users
  SET auth_user_id = new.id
  WHERE email = new.email
  AND auth_user_id IS NULL;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Custom Access Token Hook to inject gym_id and role into JWT
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb AS $$
DECLARE
  claims jsonb;
  user_record RECORD;
BEGIN
  SELECT gym_id, role INTO user_record
  FROM public.users
  WHERE auth_user_id = (event->>'user_id')::uuid;

  claims := event->'claims';

  IF user_record.gym_id IS NOT NULL THEN
    claims := jsonb_set(claims, '{gym_id}', to_jsonb(user_record.gym_id));
    claims := jsonb_set(claims, '{role}', to_jsonb(user_record.role));
  END IF;

  RETURN jsonb_set(event, '{claims}', claims);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- 5. Add Stripe customer columns to gyms
ALTER TABLE public.gyms ADD COLUMN IF NOT EXISTS stripe_customer_id text;
ALTER TABLE public.gyms ADD COLUMN IF NOT EXISTS stripe_subscription_id text;
ALTER TABLE public.gyms ADD COLUMN IF NOT EXISTS stripe_price_id text;

-- 6. Add function to get current user role
CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS text AS $$
  SELECT coalesce(auth.jwt() ->> 'role', 'member');
$$ LANGUAGE sql STABLE;

-- 7. Add function to get current user ID
CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS uuid AS $$
  SELECT coalesce(
    nullif(auth.jwt() ->> 'user_id', '')::uuid,
    nullif(auth.jwt() ->> 'sub', '')::uuid
  );
$$ LANGUAGE sql STABLE;

-- 8. Create member dashboard view
CREATE OR REPLACE VIEW public.member_dashboard_view AS
SELECT 
  m.id AS member_id,
  m.gym_id,
  m.full_name,
  m.phone,
  m.email,
  m.status,
  m.joined_on,
  m.primary_goal,
  s.id AS subscription_id,
  s.plan_id,
  s.start_date,
  s.end_date,
  s.billing_status,
  s.amount AS subscription_amount,
  p.name AS plan_name,
  p.duration_days,
  (
    SELECT count(*)::int 
    FROM public.attendance a 
    WHERE a.member_id = m.id 
    AND a.attended_on >= current_date - interval '30 days'
  ) AS attendance_last_30_days,
  (
    SELECT count(*)::int 
    FROM public.attendance a 
    WHERE a.member_id = m.id 
    AND a.attended_on = current_date
  ) AS checked_in_today
FROM public.members m
LEFT JOIN public.subscriptions s ON s.member_id = m.id AND s.billing_status = 'active'
LEFT JOIN public.plans p ON p.id = s.plan_id;

-- 9. Member check-in function
CREATE OR REPLACE FUNCTION public.member_check_in(p_member_id uuid)
RETURNS jsonb AS $$
DECLARE
  v_attendance_id uuid;
  v_already_checked boolean;
  v_gym_id uuid;
BEGIN
  SELECT EXISTS(
    SELECT 1 FROM public.attendance 
    WHERE member_id = p_member_id 
    AND attended_on = current_date
  ) INTO v_already_checked;
  
  IF v_already_checked THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Already checked in today'
    );
  END IF;
  
  SELECT gym_id INTO v_gym_id FROM public.members WHERE id = p_member_id;
  
  INSERT INTO public.attendance (gym_id, member_id, attended_on, check_in_time, source)
  VALUES (v_gym_id, p_member_id, current_date, now(), 'mobile')
  RETURNING id INTO v_attendance_id;
  
  RETURN jsonb_build_object(
    'success', true,
    'message', 'Check-in successful',
    'attendance_id', v_attendance_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 10. Demo mode helper
CREATE OR REPLACE FUNCTION public.is_demo_mode()
RETURNS boolean AS $$
BEGIN
  RETURN current_gym_id() = '00000000-0000-0000-0000-000000000001'::uuid;
END;
$$ LANGUAGE plpgsql STABLE;

-- 11. Improved RLS policies with role-based access
DROP POLICY IF EXISTS "gym scoped access on gyms" ON public.gyms;
DROP POLICY IF EXISTS "gym scoped access on users" ON public.users;
DROP POLICY IF EXISTS "gym scoped access on members" ON public.members;

-- Gyms: Only owners can modify, but all can read
CREATE POLICY "gym owners can update" ON public.gyms
  FOR UPDATE USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager')
  );

CREATE POLICY "gym read access" ON public.gyms
  FOR SELECT USING (gym_id = current_gym_id());

-- Users: Gym admins can manage
CREATE POLICY "admins can manage users" ON public.users
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager')
  );

-- Members: Gym staff can manage
CREATE POLICY "staff can manage members" ON public.members
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'trainer', 'staff')
  );

-- Plans: Gym admins can manage
CREATE POLICY "admins can manage plans" ON public.plans
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager')
  );

-- Payments: Gym staff can manage
CREATE POLICY "staff can manage payments" ON public.payments
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'staff')
  );

-- Attendance: Members can check in, staff can view all
CREATE POLICY "members can checkin" ON public.attendance
  FOR INSERT WITH CHECK (
    gym_id = current_gym_id()
  );

CREATE POLICY "staff can view attendance" ON public.attendance
  FOR SELECT USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'trainer', 'staff')
  );

-- Subscriptions: Staff can manage
CREATE POLICY "staff can manage subscriptions" ON public.subscriptions
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'staff')
  );

-- Trainers: Staff can manage
CREATE POLICY "staff can manage trainers" ON public.trainers
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager')
  );

-- Workouts: Trainers can manage
CREATE POLICY "trainers can manage workouts" ON public.workouts
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'trainer')
  );

-- Diet Plans: Trainers can manage
CREATE POLICY "trainers can manage diet_plans" ON public.diet_plans
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'trainer')
  );

-- Messages: Staff can manage
CREATE POLICY "staff can manage messages" ON public.messages
  FOR ALL USING (
    gym_id = current_gym_id() 
    AND current_user_role() IN ('owner', 'manager', 'staff')
  );

-- Allow anon for member self-service (check-in via mobile)
CREATE POLICY "allow member checkin" ON public.attendance
  FOR INSERT WITH CHECK (source = 'mobile');

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================
